services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    network_mode: host
    environment:
      TZ: "Asia/Kolkata"
      EULA: "true"
      TYPE: "LEAF"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      MODE: "survival"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 3
      LEVEL_SEED: "-1674197430"
      ONLINE_MODE: "false"
    volumes:
      - ./data:/data
    restart: unless-stopped
